# Generated by Django 3.2 on 2022-03-11 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelreview',
            name='no_of_likes',
        ),
        migrations.AlterField(
            model_name='travelreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='expedition_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
