# Generated by Django 3.2 on 2022-03-16 21:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_travelreview_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelreview',
            name='travel_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/legenduzair/image/upload/v1647465863/epic-expeditions/travel-placeholder_nx4cw2.jpg', max_length=255, verbose_name='image'),
        ),
    ]
