# Generated by Django 3.2 on 2022-03-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_travelreview_travel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelcomments',
            old_name='review_post',
            new_name='post',
        ),
    ]
