# Generated by Django 3.2 on 2022-03-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_rename_review_post_travelcomments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelreview',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
