# Generated by Django 3.2 on 2022-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_travelreview_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelreview',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
