# Generated by Django 3.2 on 2022-04-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_travelreview_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelcomments',
            name='active',
        ),
        migrations.RemoveField(
            model_name='travelcomments',
            name='email',
        ),
    ]
